### ISSUE TITLE
Support other countries than US (we are UK based)

### ISSUE THREAD

**Issue by jameslevine** [square/react-native-square-reader-sdk#103] opened 2019-11-29 14:37 UTC
### Describe the functionality you would like to see
Would like to use reader SDK in the UK for react native project.
Alternatively, please let me know an alternative that would allow me to take contactless payments on our app using the Square reader. At a very simple level all I need to do it allow a user to buy a product pay by contactless and then if that transaction is successful trigger another function in my app. Any ideas on how this might be done without this reader sdk being released for the UK?

### How would this feature make the plugin more useful?
Self-explanatory really.

**Comment by okenshields** [comment] 2019-12-04 00:15
Hi James,

Thanks for reporting the issue. Unfortunately this is a limitation of the underlying Reader SDK (which is available in the US only for now). Until a UK version Reader SDK is released, this React Native plugin won't help your scenario.
In the meantime, have you taken a look at the Square POS API and see if it can satisfy your requirements? https://developer.squareup.com/docs/pos-api/what-it-does

**Comment by StephenJosey** [comment] 2020-01-23 19:27
Please reach out to https://squareup.com/help/us/en/contact?panel=BF53A9C8EF68 if you still are interested in this. Thanks!

**Comment by StephenJosey** [comment] 2020-01-23 19:32
I also didn't realize this is a duplicate of this issue: https://github.com/square/react-native-square-reader-sdk/issues/63 so closing it out for now. Thanks!

**Closed by StephenJosey** 2020-01-23 19:32 UTC
Labels: duplicate, enhancement
